export const skiPackages = [
  // Gulmarg Packages
  {
    title: "Gulmarg Skiing Adventure",
    image: "/images/packages/ski/skier.jpg",
    location: "Gulmarg",
    duration: "6 days 5 nights",
    people: "Per Person",
    price: "₹49,999",
  },
  {
    title: "One Day Skiing Adventure",
    image: "/images/packages/ski/kahar.jpg",
    location: "Gulmarg",
    duration: "1 day",
    people: "Per Person",
    price: "₹4,999",
  },
  {
    title: "Luxury Skiing Adventure",
    image: "/images/packages/ski/chairlift.jpg",
    location: "Gulmarg",
    duration: "6 days 5 nights",
    people: "Per Person",
    price: "₹70,500",
  },
  {
    title: "Gulmarg Snowboarding Tour",
    image: "/images/packages/ski/kale.jpg",
    location: "Gulmarg",
    duration: "6 days 5 nights",
    people: "Per Person",
    price: "₹55,000",
  },
  {
    title: "One day Snowboarding Adventure",
    image: "/images/packages/ski/snowboarder.jpg",
    location: "Gulmarg",
    duration: "1 day",
    people: "Per Person",
    price: "₹5,500",
  },
  {
    title: "Luxury Snowboarding Adventure",
    image: "/images/packages/ski/board.png",
    location: "Gulmarg",
    duration: "6 days 5 nights",
    people: "Per Person",
    price: "₹80,500",
  },
  {
    title: "Snow Activities Adventure",
    image: "/images/packages/gulmarg/atv.jpg",
    location: "Gulmarg",
    duration: "1 day",
    highlights: [
      "ATV ride",
      "Snowbike ride",
      "Gondola ride",
      "Sightseeing tour",
      "Bonfire dinner",
    ],
  },
];
